image: registry.gitlab.com/pages/hugo:0.121.2

cache:
  paths:
    - public

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive  # ¡CRÍTICO!

pages:
  script:
    - hugo version
    - hugo --minify --gc
  artifacts:
    paths:
      - public
  only:
    - main